config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "/" => "home#top"

  post "login/send" => "user#login_user"
  get "login" => "user#login"
  post "signup/send" => "user#register"
  get "signup" => "user#new"

  get "user/:id/show" => "user#show"
  get 'user/edit' => 'user#edit'
  post 'user/edit/send' => 'user#edit_send'
  post "user/logout" => "user#logout"

  resources :password_reset,     only: [:new, :create, :edit]
  resources :bands

  get "submit/mic" => "submit#mic"
  post "submit/mic/send" => "submit#mic_submit"
  post "submit/mic/destroy/:id" => "submit#mic_destroy"
  get "submit/mic-list" => "submit#mic_list"
  get "submit/comment" => "submit#comment"
  get "submit/comment/list" => "submit#comment_list"
  post "submit/comment/list/destroy/:id" => "submit#comment_destroy"
  get "submit/comment/conference" => "submit#comment_conference"
  post "submit/comment/conference/send" => "submit#comment_conference_send"
  post "submit/comment/conference/get_content" => "submit#get_content"
  get "submit/comment/performance" => "submit#comment_performance"
  post "submit/comment/performance/send" => "submit#comment_performance_send"
  get "submit/comment/list/detail/:id" => "submit#comment_detail_show"
  post 'submit/comment/list/detail/:id/reply-send' => 'submit#comment_reply_send'
  post '/submit/comment/delete/:id' => 'submit#comment_reply_delete'
  get 'submit/comment/all' => 'submit#all_comment_menu'
  get 'submit/comment/all/:conf_id' => 'submit#all_comment_conf'
  get 'submit/entry' => "submit#entry_top"
  get 'submit/entry/event/:id' => "submit#entry_event"
  post 'submit/entry/event/:id/send' => "submit#entry_event_submit"
  get 'submit/entry/list' => "submit#entry_list"
	get 'submit/entry/csv-download/:event_id.csv' => 'submit#event_entry_to_csv'
  get 'submit/entry/admin' => "submit#entry_admin"
  get 'submit/entry/admin/list/:id' => "submit#entry_admin_list"

  post "submit/temporal-band/send" => "submit#temporal_band_submit"
  get "submit/temporal-band" => "submit#temporal_band"
  get "submit/room" => "submit#room"
  post "submit/room/send" => "submit#room_send"
  get "submit/room/send" => "submit#room"
  post 'submit/room/destroy/:id' => "submit#room_destroy" #部屋利用申請取り消し
  get 'submit/contact' => 'submit#contact_top'
  post 'submit/contact/send' => 'submit#contact_send'

  get "/database/bands/detail/:id" => "admin#band_detail"
  post "/database/bands/register/:id" => "admin#register_band"
  get "/database/registered-bands" => "admin#show_registered_bands"
  post "/database/bands/destroy/:id" =>"admin#band_destroy"
  get "database/temporal-bands" => "admin#show_temporal_bands"
  get "/database/show-event" => "admin#show_event"
  post "/database/add-event" => "admin#add_event"
  post "/database/event-delete/:id" => "admin#delete_event"
  get "/database/users" => "admin#show_users"
  post "/database/user/:user_id/approve" => "admin#user_approve"
  post "/database/user/:user_id/reject" => "admin#user_reject"
  post "/database/users/authority_edit/:id" => "admin#user_authority_edit"
  get "/database/notifications" => "admin#show_infos"
  post "/database/notifications/new" => "admin#add_infos"
  post '/database/notifications/delete/:id' => "admin#delete_info"
  get '/database/room-usage' => 'admin#practice_room'
  #マイク練管理
  get "/database/mic-practice" => "admin#show_mic"
  get "/database/mic-practice/unapproved" => "admin#show_unregistered_mic"
	post "/database/mic-practice/approve/:id" => "admin#mic_approve"
  post "/database/mic-practice/delete/:id" => "admin#mic_delete"
  get "/database/mic-band-detail/:id" => "admin#band_detail_mic"
  get "/database/mic-remark/:id" => "admin#mic_remark"

  get '/database/micinfo/register' => "admin#micinfo_register"
	post '/database/micinfo/register/send/confirm' => "admin#micinfo_register_send_confirm"
  post '/database/micinfo/register/send' => "admin#micinfo_register_send"
  post "/database/mic/room-register/weekly/send/:params" => "admin#microom_register"
  post "/database/mic/room-register/monthly/send" => "admin#room_monthly_send"
  get "/database" => "admin#top"
  get '/mic-order-registration/:id' => "admin#mic_order_register"
  post '/mic-order-registration/:id/:order' => "admin#mic_order_register_send"
end

app/views/admin/band_detail.html.erb
<%= render @band %>
<div class="btn-wrap">
    <%= link_to("削除", band_path(@band), {:class => "btn destroy", :method => 'DELETE', :data =>{:confirm => "#{@band.name}をデータベースから削除してよろしいですか？"}})%>
    <%= link_to("承認","/database/bands/register/#{@band.id}",{:class => "btn approve",:method => 'POST',:data => {:confirm => "バンドを正規バンドとして登録します。"}}) unless @band.registration %>
    <%= link_to("承認済",'',{:class => "btn approved"}) if @band.registration %>
</div>

<div class = "btn-wrap">
  <%= link_to("編集",edit_band_path(@band), {:class => "btn"}) %>
</div>




<ul>
  <li>${user.year} ${user.name}</li>
</ul>

app/views/admin/band_detail_mic.html.erb
<div class="band-d-wrap">
  <div class="title">バンド詳細ページ</div>

  <% if @band.band_type == 0 %>
    <div class="name"><%= @band.name %></div>
    <img src="/band-images/<%= @band.image%>" alt="">
    <div class="subtitle">バンド紹介文</div>
    <div class="description"><%= @band.description %></div>
    <div class="subtitle">結成年</div>
    <div class="description"><%= @band.year %></div>
    <div class="subtitle">メンバー</div>
    <div class="description"><% @band.band_members.each do |m|%><%= m.user.name if m%>    マイク番号<%= m.mic_number if m%><br><%end%></div>
    <div class="subtitle">バンマス,PA</div>
    <div class="description">バンマス:<%= @band.master.name %><br>PA:<%= @band.pa.name %></div>
  <% else %>
    <div class="name"><%= @band.name %></div>
    <div class="subtitle">出演イベント</div>
    <div class="description"><%= @band.event.name %></div>
    <div class="subtitle">メンバー</div>
    <div class="description"><% @band.band_members.each do |m|%><%= m.user.name if m%>    マイク番号<%= m.mic_number if m%><br><%end%></div>
    <div class="subtitle">企画責任者</div>
    <div class="description"><%= @band.master.name %></div>
  <% end %>
</div>

app/views/admin/mic_order_register.html.erb
<div class="order-inner" style="width:100%;max-width:600px;margin:80px auto;">
  <% unless Mic.select{|m| m.date == @mic.date && m.period_id == @mic.period_id && m.order == 1}.any? %>
    <%= link_to("/mic-order-registration/#{@mic.id}/1",:method => 'POST') do%>
      <div class="btn">1番目を希望する</div>
    <% end %>
  <% else %>
    <div class="btn selected"><%= Mic.select{|m| m.date == @mic.date && m.period_id == @mic.period_id && m.order == 1}.first.band.name%></div>
  <% end %>

  <% unless Mic.select{|m| m.date == @mic.date && m.period_id == @mic.period_id && m.order == 2}.any? %>
    <%= link_to("/mic-order-registration/#{@mic.id}/2",:method => 'POST') do%>
    <div class="btn">2番目を希望する</div>
    <% end %>
  <% else %>
    <div class="btn selected"><%= Mic.select{|m| m.date == @mic.date && m.period_id == @mic.period_id && m.order == 2}.first.band.name%></div>
  <% end %>

  <% unless Mic.select{|m| m.date == @mic.date && m.period_id == @mic.period_id && m.order == 3}.any?%>
    <% if Mic.where(date:@mic.date).where(period_id:@mic.period_id).count >= 3 %>
      <%= link_to("/mic-order-registration/#{@mic.id}/3",:method => 'POST') do %>
      <div class="btn">3番目を希望する</div>
      <% end %>
    <% end %>
  <% else %>
    <div class="btn selected"><%= Mic.select{|m| m.date == @mic.date && m.period_id == @mic.period_id && m.order == 3}.first.band.name%></div>
  <% end %>

</div>
<style type="text/css" media="screen">
  .btn{width:100%;background-color:salmon;color:white;font-size:16px;padding:8px;margin-top:16px;}
  .selected{background-color: white;border:solid 1px black;color:black}
</style>

app/views/admin/mic_remark.html.erb
<div class="roomreg-wrap">
  <div class="sub">マイク練備考</div>
  <div class="date"><%= @mic.date.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[@mic.date.wday]})") %>
  </div>
  <table>
    <thead>
      <tr>
        <th><%=@mic.band.name%>の<%=@mic.period.name%>マイク練の備考</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%=@mic.remark%></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/micinfo_register.html.erb
<div class="roomreg-wrap">
  <div class="sub">部屋登録画面</div>
  <div class="date"><%= @date.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[@date.wday]})") %>
  </div>
	<%= form_tag('/database/micinfo/register/send/confirm') do %>
  <table>
    <thead>
      <tr>
        <th>時限</th>
        <th>使用する部屋</th>
      </tr>
    </thead>
    <tbody>
      <% @mics.order(:period_id).map(&:period).uniq.each do |period|%>
      <tr>
        <td class="period">
          <div class="period-name"><%= period.name %></div>
        </td>
        <td>
          <% @mics.where(period:period).order(:order).each_with_index do |mic|%>
          <div class="mic-band">
            <span class="band-name"><%= mic.band.name %></span><br>
            <% if @mics.where(period:period).length == 3 %>
              <%= time_select("start_time","#{mic.id}", default: mic.start_time) %>~</br>
              <%= time_select("end_time", "#{mic.id}", default: mic.end_time) %>
              <%= select_tag "order[#{mic.id}]", options_for_select([["１番目","1"], ["2番目","2"], ["3番目","3"]], selected: mic.order.to_s) ,class: "order-select"%>
            <% elsif @mics.where(period:period).length == 2 %>
              <%= time_select("start_time","#{mic.id}", default: mic.start_time) %>~</br>
              <%= time_select("end_time", "#{mic.id}", default: mic.end_time) %>
              <%= select_tag "order[#{mic.id}]", options_for_select([["１番目","1"], ["2番目","2"]], selected: mic.order.to_s) ,class: "order-select"%>
            <% else %>
            <% end %>
          </div>
          <% end %>
          <% if @mics.find_by(period:period).room_id %>
            <%= select_tag "#{period.id}", options_for_select(Room.where(room_type:2).map{|room| ["#{room.name}","#{room.id}"]}, selected: @mics.find_by(period:period).room_id.to_s) ,class: "room-name"%>
          <% else %>
            <select name="<%= period.id %>"><option selected>選択してください</option>
-             <% Room.where(room_type:2).each do |room| %>
-               <option value="<%= room.id %>"><%=room.name%></option>
-             <% end %>
-           </select>
          <% end %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
	<input type="hidden" name="date" value="<%= @date %>">
  <%= submit_tag '情報を登録', :data => { :confirm => '情報に間違いはないですか？' } %>
	<% end %>
</div>

app/views/admin/practice_room.html.erb
<div class="room-usage-wrap">
  <div class="ru-title">部屋利用リスト</div>
  <div class="ru-desc">部屋利用者のリストを表示します。</div>
  <table>
    <tbody>
      <tr style="font-weight:bold;">
        <td>申請者</td>
        <td>部屋</td>
        <td>利用バンド</td>
        <td>時限</td>
      </tr>
      <% @dates.each do |date|%>
      <tr>
        <td colspan="4" style="background-color:#dedede;padding:4px;"><%= date.strftime("%m月%d日") %></td>
      </tr>
      <% RoomUsage.where(date: date).order('period_id').each do |usage|%>
			<% if usage %>
      <tr>
        <td><%= usage.user.name if usage.user%></td>
        <td><%= usage.room.name if usage.room %></td>
        <td><%= usage.band.name if usage.band%></td>
        <td><%= usage.period.name if usage.period %></td>
      </tr>
      <% end %>
			<% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/show_event.html.erb
<div class="show-event-wrap">
  <div class="new-info-title">サークルイベント一覧/追加</div>
  <div class="event-add-wrap">
    <%= form_tag('/database/add-event') do %>
    <div class="event-add-input-box">
      <div class="event-input-info">イベント名</div>
      <input type="text" name="name" placeholder="イベント名">
      <div class="event-input-info">イベントの種類</div>
      <select name="category">
        <option value="" disabled selected>選択してください(イベントの種類)▼</option>
        <option value="live">サークルライブ</option>
        <option value="audition">オーディション</option>
        <option value="stage">ステージイベント</option>
        <option value="conference">総会</option>
        <option value="singalong">歌う会</option>
        <option value="eigyo">営業</option>
        <option value="box-live">箱ライブ</option>
        <option value="nomikai">宴会</option>
        <option value="other">その他</option>
      </select>
      <div class="event-input-info">開催日程</div>
      <input type="date" name="date" placeholder="日程">
      <div class="event-input-info">イベント開始時間</div>
      <input type="time" name="time">
      <div class="event-input-info">エントリーの有無</div>
      <select name="entry_required">
        <option value=false disabled selected>選択してください(エントリーの有無)▼</option>
        <option value=true>エントリー必要</option>
        <option value=false>エントリー不要</option>
      </select>
       <div class="event-input-info">(エントリー有りの場合のみ)エントリーの種別</div>
      <select name="type">
        <option value=false selected>選択してください(エントリーの種別)▼</option>
        <option value="0">個人エントリー</option>
        <option value="1">正規バンドのみエントリー可</option>
        <option value="2">企画バンドのみエントリー可</option>
        <option value="3">正規・企画エントリー可</option>
      </select>
      <div class="event-input-info">コメント可能かどうか</div>
      <select name="able_to_comment">
        <option value="" disabled selected>選択してください(コメントの可否)▼</option>
        <option value="true">講評/コメント可能</option>
        <option value="false">講評/コメント不可</option>
      </select>
      <div class="event-input-info">イベントのコンテンツ（必ず、半角英数コンマ”,”でイベントを区切ってください。プログラムが判定します。）</div>
      <input type="text" name="contents" placeholder="コンマ( , )区切りでコンテンツを入力してください">
      <input type="submit" name="" class="event-submit-btn" value="イベントを追加する">
    </div>
    <% end %>
  </div>
  <div class="event-list">
    <% @events.each do |event|%>
    <div class="event-box">
      <div class="event-title"><%= event.name %></div>
      <div class="event-dt"><%= event.date.year %>年 <%= event.date.month %>月<%= event.date.day %>日   <%= event.start_time.hour %>時〜</div>
      <div class="cancel-btn"><%= form_tag("/database/event-delete/#{event.id}") do %>
        <input type="submit" value="削除">
        <%end%></div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/show_infos.html.erb
<div class="show-infos-wrapper">
  <div class="new-info-wrapper">
    <div class="new-info-contents">
      <%= form_tag("/database/notifications/new") do%>
        <div class="new-info-title">お知らせを投稿</div>
        <div class="new-info-small">お知らせの内容</div>
        <input type="text" name="content" id="new-info-content" placeholder="お知らせの内容を入力して下さい" value="<%= @notif.content %>">
        <div class="new-info-caution">お知らせは、ユーザーのトップページに反映されます。<br>正規バンドの登録は自動でお知らせに投稿されます。</div>
        <input type="submit">
      <% end %>
      <div class="new-info-title">お知らせ一覧</div>
      <div class="info-viewer">
      <% Notification.all.order('created_at DESC').each do |notif|%>
        <div class="info-viewer-content">
          <%= notif.content %><%= link_to("削除",'/database/notifications/delete/' + notif.id.to_s , {:method => 'POST',data: {confirm: "本当に削除しますか？"}})%>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/show_mic.html.erb
<div class="mic-admin-wrapper">

  <div class="mic-title">
    <div class="mic-title-box">
      <h1>マイク練管理</h1>
    </div>
  </div>

  <div class="mic-main-wrapper">
    <div class="mic-description">
      ・ステータスを変更すると、マイク練申請者にメールが届きます。<br>
      ・承認ボタンは確認してから押してください。
      <%= link_to "・未承認マイク練はこちら", "/database/mic-practice/unapproved", class: "unregistered" %>
    </div>
  </div>


  <% mics = Mic.order("date ASC, period_id ASC").select {|m| m.date >= Date.today} %>
    <div class="mic">
    <% mics.map(&:date).uniq.each do |date|%>
      <div class="mic">
      <div class="date"> <%= date.strftime("%m月%d日" + "(#{%w(日 月 火 水 木 金 土)[date.wday]})") %>
      </div>
      <div class="date-mics<%= " today" if date == Date.today %>">
      <% mics.select {|m| m.date == date}.each do |mic|%>
        <div class="mic-admin-band">
          <div class="left">
            <div class="period"><%= mic.period.name%>
              <% if mic.order && (mic.order != 0) %>
                <%= "分割#{mic.order}番目" %>
              <% end %>
              <% if mic.remark != "" && mic.remark %>
                <div class="mic-remark">
                  <%= link_to("備考あり","/database/mic-remark/#{mic.id}") %>
                </div>
              <% end %>
              <% if mic.room %>
                <%= link_to("#{mic.room.name}",database_micinfo_register_path(date:mic.date)) %>
              <% else %>
                <%= link_to("部屋を登録する",database_micinfo_register_path(date:mic.date)) %>
              <% end %>
            </div>

            <% if mic.band.band_type == 0 %>
              <div class="band-pa"><%= link_to "#{mic.band.name}", "/database/mic-band-detail/#{mic.band.id}", class: "band-name" %> (PA:<%= mic.band.pa.name %>
                <% if mic.paattendance == "不参加" %>
                  <span class="attendence-alert"><%= mic.paattendance %></span>
                <% else %>
                  <%= mic.paattendance %>
                <% end %>)</div>
              <!-- <div class="created-at">申請日時: <%= mic.created_at.strftime("%m月%d日 %H:%M")%></div> -->
              <a href="mailto:<%= mic.band.master.email %>">バンマスに連絡：<%=mic.band.master.name%></a>
            <% else %>
              <div class="band-pa"><%= link_to "#{mic.band.name}", "/database/mic-band-detail/#{mic.band.id}", class: "band-name" %></div>
              <!-- <div class="created-at">申請日時: <%= mic.created_at.strftime("%m月%d日 %H:%M")%></div> -->
              <a href="mailto:<%= mic.band.master.email %>">企画責任者に連絡：<%=mic.band.master.name%></a>
            <% end %>

          </div>
				  <div class="right-delete">
            <%= link_to('削除',"/database/mic-practice/delete/#{mic.id}",{method: 'POST',class: "delete-btn",data:{confirm: "本当に削除しますか？"}}) %>
          </div>
          <div class="right-approve">
            <%= link_to('承認',"/database/mic-practice/approve/#{mic.id}",{method: 'POST',class: "approve-btn",data:{confirm: "本当に承認しますか？"}}) if mic.status.to_i == 0%>
            <% if mic.status.to_i == 1 %>
              <a class="approve-btn approved">承認済</a>
            <% end %>
          </div>
        </div>
      <% end %>
      </div>
      </div>
    <% end %>

</div>

app/views/admin/show_registered_bands.html.erb
<div class="band-show-wrapper">
  <div class="band-show-inner">
    <div class="band-show-title">正規バンド一覧</div>
    <div class="band-show-description">
      正規バンド申請の取り消し・情報の変更などはここから行ってください。
    </div>
    <div class="submenu">申請中のバンド</div>
    <% Band.where(registration:false, band_type:0).each do |band|%>
      <%= link_to(band.name,"/database/bands/detail/#{band.id}",{class: "link"})%>
    <% end %>
    <div class="submenu">登録されているバンド</div>
    <div class="band-show-container">
      <div class="mic-admin-wrapper">
        <% mics = Mic.order("date ASC, period_id ASC").select {|m| m.date >= Date.today} %>
          <% 4.times do |i|%>
            <div class="mic">
            <div class="date"> <%= @years[i] %>
            </div>
            <div class="date-mics">
            <% @bands_by_year[i].each do |band|%>
              <div class="mic-admin-band">
                <div class="left">
                  <div class="band-pa"><%= link_to(band.name,band_path(band),{class: "band-name"})%></div>
                </div>
                <div class="right-delete">
                  <%= link_to("削除", band_path(band), {:class => "delete-btn", :method => 'DELETE', :data =>{:confirm => "#{band.name}を正規バンドから外してよろしいですか？"}})%>
                </div>
                <div class="right-approve">
                  <%= link_to("編集", edit_band_path(band), {:class => "approve-btn", :data => {:confirm => "webマスター権限で編集します。よろしいですか？"}}) %>
                </div>
              </div>
            <% end %>
            </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/show_temporal_bands.html.erb
<div class="showtemp-wrapper">
  <h1>企画バンド管理</h1>
  <div class="showtemp-contents">
	<% @events.each do |event|%>
	<div class="showtemp-event"><%= event.name %></div>
    <% event.bands.each do |band|%>
      <div class="showtemp-content">
        <p style="font-size:20px;font-weight:bold;display:inline;"><%= band.name %></p><br>

      </div>
    <% end %>
	<% end %>
  </div>
</div>

app/views/admin/show_unregistered_mic.html.erb
<div class="mic-admin-wrapper">

  <div class="mic-title">
    <div class="mic-title-box">
      <h1>未承認マイク練</h1>
    </div>
  </div>

  <div class="mic-main-wrapper">
    <div class="mic-description">
      ・ステータスを変更すると、マイク練申請者にメールが届きます。<br>
      ・承認ボタンは確認してから押してください。
    </div>
  </div>

  <% mics = Mic.where(status: 0).order("date ASC, period_id ASC").select {|m| m.date >= Date.today} %>
    <div class="mic">
    <% mics.map(&:date).uniq.each do |date|%>
    <div class="mic">
      <div class="date"> <%= date.strftime("%m月%d日" + "(#{%w(日 月 火 水 木 金 土)[date.wday]})") %>
      </div>
      <% mics.select {|m| m.date == date}.each do |mic|%>
        <div class="mic-admin-band">
          <div class="left">
            <div class="period"><%= mic.period.name%>
              <% if mic.order %>
                <%= "分割#{mic.order}番目" %>
              <% end %>
              <% if mic.remark != "" && mic.remark %>
                <div class="mic-remark">
                  <%= link_to("備考あり","/database/mic-remark/#{mic.id}") %>
                </div>
              <% end %>
              <% if mic.room %>
                <%= link_to("#{mic.room.name}",database_micinfo_register_path(date:mic.date)) %>
              <% else %>
                <%= link_to("部屋を登録する",database_micinfo_register_path(date:mic.date)) %>
              <% end %>
            </div>

            <% if mic.band.band_type == 0 %>
              <div class="band-pa"><%= link_to "#{mic.band.name}", "/database/mic-band-detail/#{mic.band.id}", class: "band-name" %> (PA:<%= mic.band.pa.name %>
                <% if mic.paattendance == "不参加" %>
                  <span class="attendence-alert"><%= mic.paattendance %></span>
                <% else %>
                  <%= mic.paattendance %>
                <% end %>)</div>
              <!-- <div class="created-at">申請日時: <%= mic.created_at.strftime("%m月%d日 %H:%M")%></div> -->
              <a href="mailto:<%= mic.band.master.email %>">バンマスに連絡：<%=mic.band.master.name%></a>
            <% else %>
              <div class="band-pa"><%= link_to "#{mic.band.name}", "/database/mic-band-detail/#{mic.band.id}", class: "band-name" %></div>
              <!-- <div class="created-at">申請日時: <%= mic.created_at.strftime("%m月%d日 %H:%M")%></div> -->
              <a href="mailto:<%= mic.band.master.email %>">企画責任者に連絡：<%=mic.band.master.name%></a>
            <% end %>

          </div>
          <div class="right-delete">
            <%= link_to('削除',"/database/mic-practice/delete/#{mic.id}",{method: 'POST',class: "delete-btn",data:{confirm: "本当に削除しますか？"}}) %>
          </div>
          <div class="right-approve">
            <%= link_to('承認',"/database/mic-practice/approve/#{mic.id}",{method: 'POST',class: "approve-btn",data:{confirm: "本当に承認しますか？"}}) if mic.status.to_i == 0%>
            <% if mic.status.to_i == 1 %>
              <a class="approve-btn approved">承認済</a>
            <% end %>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>

</div>

app/views/admin/show_users.html.erb
<div class="database-users-wrapper">
<div class="user-show-description">
  <h1>ユーザー管理画面</h1>
  <div class="user-description-box">ユーザーの管理ができます。データベースにアクセスできる管理者の権限を更新する場合管理者権限のセル内の「編集」ボタンを押してください。</div>
</div>
<div class="user-display-grid">
  <% @users.each do |user|%>
  <div class="user-display">
    <div class="user-display-inner">
      <div class="user-display-basic">
        <div class="user-display-name"><%= user.name %></div>
        <div class="user-display-univ"><%= user.univ %></div>
        <div class="user-display-year"><%= user.year %>年度入会(<%= Date.today.year - user.year + 1 if Date.today.mon > 3%>
                                                                   <%= Date.today.year - user.year if Date.today.mon <= 3  %>年目)</div>
      </div>
      <div class="user-display-contact">
        <div class="user-display-tel"><i class="fa fa-phone"></i> <%= user.tel %></div>
        <div class="user-display-email"><i class="fa fa-envelope-o"></i><%= user.email %></div>
        <div class="user-display-authority"><i class="fa fa-user-plus"></i>
        <% if user.authority == nil %>
          一般サークル員
        <% elsif user.authority == "admin"%>
          ポータル管理者
        <% elsif user.authority == "producer"%>
          サークルライブプロデューサー
        <% elsif user.authority == "mic"%>
          音響セクション員(マイク練管理者)
        <% end %>
        <button class="open-modal" type="button" data-toggle="modal" data-target=".modal" data-id="<%= user.id %>" data-name="<%= user.name %>">編集</button>
        <% if user.approval == false %>
        <%= link_to("承認",'/database/user/' + user.id.to_s + '/approve',method: 'post',class: "approve-button", data: {confirm: "本当に承認しますか？"}) %><%= link_to("拒否",'/database/user/' + user.id.to_s + '/reject',method: 'post',class: "approve-button", data: {confirm: "本当に拒否しますか？"}) %>
        <% else %>
        <div class="approve-button">承認済み</div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

  <div class="modal">
    <div class="modal-close"><i class="fa fa-times"></i></div>
    <div class="modal-title"> さんの権限を変更</div>
    <form action="#" method="post">
    <div class="modal-select">
      <select name="authority">
        <option value="" disabled selected>選択して下さい▼</option>
        <option value="admin">WEB管理者</option>
        <option value="producer">プロデューサー</option>
        <option value="mic">マイク練管理</option>
        <option value="nil">なし</option>
      </select>
    </div>
    <input type="submit" name="user_id" value="変更する" class="authchange-submit-btn">
    </form>
  </div>
</div>