config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "/" => "home#top"

  post "login/send" => "user#login_user"
  get "login" => "user#login"
  post "signup/send" => "user#register"
  get "signup" => "user#new"

  get "user/:id/show" => "user#show"
  get 'user/edit' => 'user#edit'
  post 'user/edit/send' => 'user#edit_send'
  post "user/logout" => "user#logout"

  resources :password_reset,     only: [:new, :create, :edit]
  resources :bands

  get "submit/mic" => "submit#mic"
  post "submit/mic/send" => "submit#mic_submit"
  post "submit/mic/destroy/:id" => "submit#mic_destroy"
  get "submit/mic-list" => "submit#mic_list"
  get "submit/comment" => "submit#comment"
  get "submit/comment/list" => "submit#comment_list"
  post "submit/comment/list/destroy/:id" => "submit#comment_destroy"
  get "submit/comment/conference" => "submit#comment_conference"
  post "submit/comment/conference/send" => "submit#comment_conference_send"
  post "submit/comment/conference/get_content" => "submit#get_content"
  get "submit/comment/performance" => "submit#comment_performance"
  post "submit/comment/performance/send" => "submit#comment_performance_send"
  get "submit/comment/list/detail/:id" => "submit#comment_detail_show"
  post 'submit/comment/list/detail/:id/reply-send' => 'submit#comment_reply_send'
  post '/submit/comment/delete/:id' => 'submit#comment_reply_delete'
  get 'submit/comment/all' => 'submit#all_comment_menu'
  get 'submit/comment/all/:conf_id' => 'submit#all_comment_conf'
  get 'submit/entry' => "submit#entry_top"
  get 'submit/entry/event/:id' => "submit#entry_event"
  post 'submit/entry/event/:id/send' => "submit#entry_event_submit"
  get 'submit/entry/list' => "submit#entry_list"
	get 'submit/entry/csv-download/:event_id.csv' => 'submit#event_entry_to_csv'
  get 'submit/entry/admin' => "submit#entry_admin"
  get 'submit/entry/admin/list/:id' => "submit#entry_admin_list"

  post "submit/temporal-band/send" => "submit#temporal_band_submit"
  get "submit/temporal-band" => "submit#temporal_band"
  get "submit/room" => "submit#room"
  post "submit/room/send" => "submit#room_send"
  get "submit/room/send" => "submit#room"
  post 'submit/room/destroy/:id' => "submit#room_destroy" #部屋利用申請取り消し
  get 'submit/contact' => 'submit#contact_top'
  post 'submit/contact/send' => 'submit#contact_send'

  get "/database/bands/detail/:id" => "admin#band_detail"
  post "/database/bands/register/:id" => "admin#register_band"
  get "/database/registered-bands" => "admin#show_registered_bands"
  post "/database/bands/destroy/:id" =>"admin#band_destroy"
  get "database/temporal-bands" => "admin#show_temporal_bands"
  get "/database/show-event" => "admin#show_event"
  post "/database/add-event" => "admin#add_event"
  post "/database/event-delete/:id" => "admin#delete_event"
  get "/database/users" => "admin#show_users"
  post "/database/user/:user_id/approve" => "admin#user_approve"
  post "/database/user/:user_id/reject" => "admin#user_reject"
  post "/database/users/authority_edit/:id" => "admin#user_authority_edit"
  get "/database/notifications" => "admin#show_infos"
  post "/database/notifications/new" => "admin#add_infos"
  post '/database/notifications/delete/:id' => "admin#delete_info"
  get '/database/room-usage' => 'admin#practice_room'
  #マイク練管理
  get "/database/mic-practice" => "admin#show_mic"
  get "/database/mic-practice/unapproved" => "admin#show_unregistered_mic"
	post "/database/mic-practice/approve/:id" => "admin#mic_approve"
  post "/database/mic-practice/delete/:id" => "admin#mic_delete"
  get "/database/mic-band-detail/:id" => "admin#band_detail_mic"
  get "/database/mic-remark/:id" => "admin#mic_remark"

  get '/database/micinfo/register' => "admin#micinfo_register"
	post '/database/micinfo/register/send/confirm' => "admin#micinfo_register_send_confirm"
  post '/database/micinfo/register/send' => "admin#micinfo_register_send"
  post "/database/mic/room-register/weekly/send/:params" => "admin#microom_register"
  post "/database/mic/room-register/monthly/send" => "admin#room_monthly_send"
  get "/database" => "admin#top"
  get '/mic-order-registration/:id' => "admin#mic_order_register"
  post '/mic-order-registration/:id/:order' => "admin#mic_order_register_send"
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to '/'
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update(password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])
      flash[:notice] = "パスワードを変更しました。"
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def get_user
      @user = User.find_by(email: params[:email])
    end

    # 正しいユーザーかどうか確認する
  def valid_user
    unless (@user && @user.approval)
      redirect_to '/'
    end
  end
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_reset/edit.html.erb
<div class="signup-wrapper">
  <h1>パスワード再登録</h1>
  <div class="form-wrapper">

    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <div class="signup-form">
        <%= hidden_field_tag :email, @user.email %>
        <div class="signup-content-small">パスワード(6文字以上) <span>※必須</span></div>
        <%= f.password_field :password, class: 'form-control' %>
        <div class="signup-content-small">パスワード再入力 <span>※必須</span></div>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <div class="signup-rule">
          ・パスワードや個人情報は漏れることのないよう大切に保管して下さい。<br>
          ・悪意のある利用・機能外の個人的な利用は控えて下さい。<br>
        </div>
        <%= f.submit "再登録", class: "signup-btn" %>
      </div>
    <% end %>


  </div>
</div>

app/views/password_reset/new.html.erb
<div class="main-wrapper-login">
<div class="login-wrapper">
  <h1>パスワード変更</h1>
  <div class="login-content-wrapper">
    <div class="login-content login-title">
      <h1>SCS Portal</h1>
    </div>
    <div class="login-content signin-box">
      <p id="login-with-account">変更用リンクの送信先※Portalアカウントのアドレス</p>

      <!-- <%= form_tag("/user/password/sent") do %>
        <input type="email" name="email" class="login-input login-email-input" value="<%= @email %>" placeholder="Emailアドレスを入力">
        <p id="show-pass"></p>
        <% if @error != nil %>
          <div class="login-error-message"><%= @error %></div>
        <% end %>
        <input type="submit" id="login-btn" value="送信">
      <% end %> -->

      <%= form_for(:password_reset, url: password_reset_index_path) do |f| %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'login-input login-email-input' %>

        <%= f.submit "送信", id: "login-btn" %>
      <% end %>

      <a href="/signup" class="btn" id="signup-btn">新規会員登録はこちら</a>
    </div>
  </div>
</div>
</div>