config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "/" => "home#top"

  post "login/send" => "user#login_user"
  get "login" => "user#login"
  post "signup/send" => "user#register"
  get "signup" => "user#new"

  get "user/:id/show" => "user#show"
  get 'user/edit' => 'user#edit'
  post 'user/edit/send' => 'user#edit_send'
  post "user/logout" => "user#logout"

  resources :password_reset,     only: [:new, :create, :edit]
  resources :bands

  get "submit/mic" => "submit#mic"
  post "submit/mic/send" => "submit#mic_submit"
  post "submit/mic/destroy/:id" => "submit#mic_destroy"
  get "submit/mic-list" => "submit#mic_list"
  get "submit/comment" => "submit#comment"
  get "submit/comment/list" => "submit#comment_list"
  post "submit/comment/list/destroy/:id" => "submit#comment_destroy"
  get "submit/comment/conference" => "submit#comment_conference"
  post "submit/comment/conference/send" => "submit#comment_conference_send"
  post "submit/comment/conference/get_content" => "submit#get_content"
  get "submit/comment/performance" => "submit#comment_performance"
  post "submit/comment/performance/send" => "submit#comment_performance_send"
  get "submit/comment/list/detail/:id" => "submit#comment_detail_show"
  post 'submit/comment/list/detail/:id/reply-send' => 'submit#comment_reply_send'
  post '/submit/comment/delete/:id' => 'submit#comment_reply_delete'
  get 'submit/comment/all' => 'submit#all_comment_menu'
  get 'submit/comment/all/:conf_id' => 'submit#all_comment_conf'
  get 'submit/entry' => "submit#entry_top"
  get 'submit/entry/event/:id' => "submit#entry_event"
  post 'submit/entry/event/:id/send' => "submit#entry_event_submit"
  get 'submit/entry/list' => "submit#entry_list"
	get 'submit/entry/csv-download/:event_id.csv' => 'submit#event_entry_to_csv'
  get 'submit/entry/admin' => "submit#entry_admin"
  get 'submit/entry/admin/list/:id' => "submit#entry_admin_list"

  post "submit/temporal-band/send" => "submit#temporal_band_submit"
  get "submit/temporal-band" => "submit#temporal_band"
  get "submit/room" => "submit#room"
  post "submit/room/send" => "submit#room_send"
  get "submit/room/send" => "submit#room"
  post 'submit/room/destroy/:id' => "submit#room_destroy" #部屋利用申請取り消し
  get 'submit/contact' => 'submit#contact_top'
  post 'submit/contact/send' => 'submit#contact_send'

  get "/database/bands/detail/:id" => "admin#band_detail"
  post "/database/bands/register/:id" => "admin#register_band"
  get "/database/registered-bands" => "admin#show_registered_bands"
  post "/database/bands/destroy/:id" =>"admin#band_destroy"
  get "database/temporal-bands" => "admin#show_temporal_bands"
  get "/database/show-event" => "admin#show_event"
  post "/database/add-event" => "admin#add_event"
  post "/database/event-delete/:id" => "admin#delete_event"
  get "/database/users" => "admin#show_users"
  post "/database/user/:user_id/approve" => "admin#user_approve"
  post "/database/user/:user_id/reject" => "admin#user_reject"
  post "/database/users/authority_edit/:id" => "admin#user_authority_edit"
  get "/database/notifications" => "admin#show_infos"
  post "/database/notifications/new" => "admin#add_infos"
  post '/database/notifications/delete/:id' => "admin#delete_info"
  get '/database/room-usage' => 'admin#practice_room'
  #マイク練管理
  get "/database/mic-practice" => "admin#show_mic"
  get "/database/mic-practice/unapproved" => "admin#show_unregistered_mic"
	post "/database/mic-practice/approve/:id" => "admin#mic_approve"
  post "/database/mic-practice/delete/:id" => "admin#mic_delete"
  get "/database/mic-band-detail/:id" => "admin#band_detail_mic"
  get "/database/mic-remark/:id" => "admin#mic_remark"

  get '/database/micinfo/register' => "admin#micinfo_register"
	post '/database/micinfo/register/send/confirm' => "admin#micinfo_register_send_confirm"
  post '/database/micinfo/register/send' => "admin#micinfo_register_send"
  post "/database/mic/room-register/weekly/send/:params" => "admin#microom_register"
  post "/database/mic/room-register/monthly/send" => "admin#room_monthly_send"
  get "/database" => "admin#top"
  get '/mic-order-registration/:id' => "admin#mic_order_register"
  post '/mic-order-registration/:id/:order' => "admin#mic_order_register_send"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :room_usages, dependent: :destroy
  has_many :mics, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :band_members, dependent: :destroy
  has_many :bands, through: :band_members, dependent: :destroy
  has_one :master, class_name: 'Band', foreign_key: 'master_id'
  has_one :pa, class_name: 'Band', foreign_key: 'pa_id'
  attr_accessor :remember_token, :activation_token, :reset_token
	validates :email, presence: true,uniqueness: true
  validates :tel, presence: true
  validates :year, presence: true
  validates :name, presence: true
  validates :password_digest, presence: true
  validates :section, presence: true
  validates :univ, presence: true
  has_secure_password validations: false

  # def temporal_bands
  #   user_bands = Array.new()
  #   TemporalBand.all.each do |band|
  #     if band.members.include?(self.name)
  #         user_bands.push(band)
  #     end
  #   end
  #   return user_bands
  # end

  def password_confirmation_failure
      errors.add(:password, "が確認用と一致しません")
  end

  def name_space_validation
    if self.name.include?(" ") || self.name.include?("　")
      errors.add(:name, "にスペースが含まれています")
      return false
    else
      return true
    end
  end

  def band_names
    user_bands_name = Array.new()
    self.bands.each do |band|
      user_bands_name.push(band.name)
    end
    return user_bands_name
  end



  def change_status_to_ob_if_graduated
    #2018年4月1日0:00に2014入会のステータスを全員分OBにする
    current_year = Date.today.year
    graduating_year = current_year - 4
    graduates = User.where(year: graduating_year)
    graduates.each do |graduate|
      graduate.status = "OB"
      graduate.save
    end
  end

  def self.digest(string)
    #暗号化
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    #ランダムなトークンを生成する
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    #remember_tokenにランダムなトークンを保存
    update_attribute(:remember_digest,User.digest(remember_token))
    #remember_digestにremember_tokenをBCryptで暗号化したものを保存
  end

  def authenticated?(remember_token)
    if remember_digest
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    #remember_digestは、remember_tokenを暗号化したものか問う
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  #パスワード再設定用
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

end

app/controllers/user_controller.rb
#encoding: utf-8

class UserController < ApplicationController

  def login
    @user = User.new(email:"")
    @email = ""
    @error = nil
    if @current_user
      redirect_to("/user/#{@current_user.id}/show")
    end
  end

  def login_user
    if User.find_by(email: params[:email])
      @user = User.find_by(email: params[:email])
      unless @user.authenticate(params[:password])
        @error = "パスワードが違います"
      end
    else
      @error = "Emailが違います"
    end
    if @user == nil || !@user.authenticate(params[:password])
      @email = params[:email]
      render("login")
    else
      @user.remember
      cookies.permanent.signed[:user_id] = @user.id
      cookies.permanent[:remember_token] = @user.remember_token
      if (session_id = session[:user_id])
        redirect_to("/user/#{session_id}/show")
      elsif (cookie_id = cookies.signed[:user_id])
        redirect_to("/user/#{cookie_id}/show")
      end
    end
  end

  def new
    @user = User.new()
    @errors = [""]
  end

  def register
    if params[:year] == ""
      year = nil
    else
      year = params[:year].to_i
    end
    @user = User.new(name: params[:name],
      email: params[:email],
      tel: params[:tel],
      year: year,
      univ: params[:univ],
      password: params[:password],
      section: params[:section])
    @user.name_space_validation
    if @user.save && params[:password] == params[:password_confirmation] && @user.name_space_validation
      session[:user_id] = @user.id
      redirect_to("/")
      flash[:notice] = "ログインしました"
      UserMailer.user_verification_mail(@user).deliver
      UserMailer.user_verification_mail_to_admin(@user).deliver
    else
      if params[:password] != params[:password_confirmation]
        @user.password_confirmation_failure
      end
      @user.name_space_validation
      flash[:notice] = "入力内容にエラーがあります"
      render("new")
    end
  end

  def show
		self.user_authentificate
    if (session_user = User.find_by(id: session[:user_id]))
      @user = session_user
    elsif (cookie_user = User.find_by(id: cookies.signed[:user_id]))
      @user = cookie_user
    end
    @notifs = Notification.order(created_at: "DESC").limit(5)
  end

  def logout
    @current_user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました。"
    redirect_to("/")
  end

  def edit
    @user = @current_user
  end

  def edit_send
    @user = @current_user
    if @user.update(
      name: params[:name],
      email: params[:email],
      year: params[:year],
      tel: params[:tel],
      univ: params[:univ],
      section: params[:section]
    )
      flash[:notice] = "内容を変更しました。"
      redirect_to("/user/#{@current_user.id}/show")
    else
      flash[:notice] = "変更できませんでした。内容を確認してください"
      render('user/edit')
    end
  end

  def password_reset_sender
  end

  def password_reset_sent
    @user = User.find_by(email:params[:email])
    UserMailer.password_reset_mail(@user).deliver
    flash[:notice] = "メールを送信しました。確認してください。"
    render :file => "/home/top"
  end

  def password_reset
  end

  def password_reset_done
    if params[:password] == params[:passwordagain]
      @user = User.find_by(id: params[:id])
      @user.update_attribute(password: params[:password])
      flash[:notice] = "変更されました。"
      redirect_to("login")
    else
      flash[:notice] = "再入力されたパスワードが一致しません。"
      redirect_to("/user/#{params[:id]}/password")
    end
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<div class="edit-inner">
  <div class="edit-title">ユーザー情報の編集</div>
  <div class="edit-form">
    <%= form_tag('/user/edit/send') do %>
    <div class="edit-form-content">氏名(スペースを開けないでください)</div>
    <input type="text" name="name" value="<%=@current_user.name%>">
    <div class="edit-form-content">Email</div>
    <input type="email" name="email" value="<%=@current_user.email%>">
    <div class="edit-form-content">入会年度</div>
    <input type="text" name="year" value="<%=@current_user.year%>">
    <div class="edit-form-content">携帯電話番号</div>
    <input type="tel" name="tel" value="<%=@current_user.tel%>">
    <div class="edit-form-content">大学</div>
    <input type="text" name="univ" value="<%=@current_user.univ%>">
    <div class="edit-form-content">セクション</div>
    <select name="section" >
        <% if @user.section == nil %>
            <option value="" selected disabled>選択してください</option>
        <% end %>
        <% if @user.section == "舞台監督" %>
            <option value="舞台監督" selected>舞台監督</option>
        <% else %>
            <option value="舞台監督">舞台監督</option>
        <% end %>
        <% if @user.section == "音響" %>
            <option value="音響" selected>音響</option>
        <% else %>
            <option value="音響">音響</option>
        <% end %>
        <% if @user.section == "照明" %>
            <option value="照明" selected>照明</option>
        <% else %>
            <option value="照明">照明</option>
        <% end %>
        <% if @user.section == "舞台美術" %>
            <option value="舞台美術" selected>舞台美術</option>
        <% else %>
            <option value="舞台美術">舞台美術</option>
        <% end %>
        <% if @user.section == "インカム" %>
            <option value="インカム" selected>インカム</option>
        <% else %>
            <option value="インカム">インカム</option>
        <% end %>
        <% if @user.section == "TK" %>
            <option value="TK" selected>TK</option>
        <% else %>
            <option value="TK">TK</option>
        <% end %>
        <% if @user.section == "会場" %>
            <option value="会場" selected>会場</option>
        <% else %>
            <option value="会場">会場</option>
        <% end %>
        <% if @user.section == "渉外" %>
            <option value="渉外" selected>渉外</option>
        <% else %>
            <option value="渉外">渉外</option>
        <% end %>
        <% if @user.section == "広報" %>
            <option value="広報" selected>広報</option>
        <% else %>
            <option value="広報">広報</option>
        <% end %>
        <% if @user.section == "デザイン" %>
            <option value="デザイン" selected>デザイン</option>
        <% else %>
            <option value="デザイン">デザイン</option>
        <% end %>
        <% if @user.section == "記録" %>
            <option value="記録" selected>記録</option>
        <% else %>
            <option value="記録">記録</option>
        <% end %>
        <% if @user.section == "宴会" %>
            <option value="宴会" selected>宴会</option>
        <% else %>
            <option value="宴会">宴会</option>
        <% end %>
    </select>
    <% if @user.errors.any?%>
        <div class="edit-error-display">
            <% @user.errors.full_messages do |message|%>
                <%= message %><br>
            <% end %>
        </div>
    <% end %>
    <input type="submit" name="" value="変更する">
    <% end %>
  </div>
</div>

app/views/user/login.html.erb
<div class="main-wrapper-login">
<div class="login-wrapper">
  <h1>ログイン</h1>
  <div class="login-content-wrapper">
    <div class="login-content login-title">
      <h1>SCS Portal</h1>
    </div>
    <div class="login-content signin-box">
      <p id="login-with-account">SCSアカウントでログイン</p>

      <%= form_tag("/login/send") do %>
        <input type="email" name="email" class="login-input login-email-input" value="<%= @email %>" placeholder="Emailアドレスを入力">
        <input type="password" name="password" class="login-input" placeholder="パスワードを入力">
        <p id="show-pass"><input id="pass-checkbox" type="checkbox" name="">パスワードを表示する</p>
        <% if @error != nil %>
          <div class="login-error-message"><%= @error %></div>
        <% end %>
        <input type="submit" id="login-btn" value="ログイン">
      <% end %>
      <a href="/signup" class="btn" id="signup-btn">新規会員登録はこちら</a>
      <a href="/signup" class="btn" id="forgotten-btn">パスワードをお忘れの方へ</a>
    </div>
  </div>
</div>
</div>

app/views/user/new.html.erb
<div class="signup-wrapper">
  <h1>新規登録</h1>
  <div class="form-wrapper">
    <%= form_tag("/signup/send") do %>
      <div class="signup-form">
        <% if @user.errors.any? %>
            <div class="mic-form-errors">
                <% @user.errors.full_messages.each do |message| %>
                    <%= message %><br>
                <% end %>
            </div>
        <% end %>
        <div class="signup-content">個人情報登録</div>
        <div class="signup-content-small">氏名<strong>(スペースなし)</strong> <span>※必須</span></div>
        <input type="text" name="name" placeholder="氏名を入力(スペースなし)" value=<%=@user.name%>>
        <div class="signup-content-small">Emailアドレス <span>※必須</span></div>
        <input type="email" name="email" placeholder="普段使用するメールアドレスを入力してください" value=<%=@user.email%>>
        <div class="signup-content-small">電話番号(ハイフンなし) <span>※必須</span></div>
        <input type="text" name="tel" placeholder="電話番号をハイフンなしで入力してください" value=<%=@user.tel%>>
        <div class="signup-content">その他の情報</div>
        <div class="signup-content-small">SCSに入会した年度 <span>※必須</span></div>
        <input type="text" name="year" placeholder="半角数字 例)2016" value=<%=@user.year%>>
        <div class="signup-content-small">セクション <span>※必須</span></div>
        <select name="section" class = "section_select">
            <option value="" selected disabled>選択してください</option>
            <option value="新人ライブプロデューサー">新人ライブプロデューサー</option>
            <option value="舞台監督">舞台監督</option>
            <option value="音響">音響</option>
            <option value="照明">照明</option>
            <option value="舞台美術">舞台美術</option>
            <option value="インカム">インカム</option>
            <option value="TK">TK</option>
            <option value="会場">会場</option>
            <option value="渉外">渉外</option>
            <option value="広報">広報</option>
            <option value="デザイン">デザイン</option>
            <option value="記録">記録</option>
            <option value="宴会">宴会</option>
        </select>
        <div class="signup-content-small">大学名 <span>※必須</span></div>
        <input type="text" name="univ" placeholder="例)早稲田大学" value=<%=@user.univ%>>
        <div class="signup-content">パスワード登録</div>
        <div class="signup-content-small">パスワード(6文字以上) <span>※必須</span></div>
        <input type="password" name="password" placeholder="パスワードを登録">
        <div class="signup-content-small">パスワード再入力 <span>※必須</span></div>
        <input type="password" name="password_confirmation" placeholder="パスワードを再入力">
        <div class="signup-rule">
          ・パスワードや個人情報は漏れることのないよう大切に保管して下さい。<br>
          ・管理者権限が与えられる場合は、SCSサークル員以外のユーザーを登録しないよう留意して下さい。<br>
          ・申請フォームなどの入力は、取り消しが可能ですが、慎重に行うようお願いします。<br>
          ・悪意のある利用・機能外の個人的な利用は控えて下さい。<br>
        </div>
        <input type="submit" class="signup-btn" value="新規登録">
      </div>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<div class="user-show-wrapper">
  <div class="user-show-higher-wrapper">
    <div class="user-title">Street Corner Symphony</div>
    <div class="user-sub-title">Web版SCSポータル</div>
    <div class="user-show-box">
      <div class="user-show-contents">
        <div class="user-show-image">
        </div>
        <div class="user-show-informations">
          <div class="user-show-content-name"><%= @user.name + "(#{@user.year}年度入会)" %></div>
          <div class="user-show-content"><%= @user.email %></div>
          <div class="user-show-logout"><%= link_to("ログアウト","/user/logout",{method: :post, :class => "logout-link"})%></div>
          <div class="user-show-logout"><%= link_to("ユーザー情報編集","/user/edit",:class => "logout-link")%></div>
          <% if @user.authority == "admin" %>
            <div class="user-show-logout"><%= link_to("管理画面へ","/database",:class => "logout-link")%></div>
          <% elsif @user.authority == "mic" %>
            <div class="user-show-logout"><%= link_to("マイク練管理画面へ","/database/mic-practice",:class => "logout-link")%></div>
          <% else %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="notice-wrapper">
      <div class="user-menu-title notice-title">お知らせ</div>
      <% if @notifs.count != 0 %>
      <% @notifs.each do |notif|%>
        <div class="notice-content">
          <%= notif.date.strftime("%m月%d日") + notif.time.strftime("%H:%M") %><br>
          <%= notif.content%>
        </div>
      <% end %>
      <% end %>
      </div>
    <div class="user-menu-wrapper">
    <div class="user-menu-title">メニュー</div>
      <%= link_to("/submit/mic") do %>
      <div class="user-menu-content">
        <div class="menu-content-img"></div>
        <div class="menu-content-title">マイク練予約</div>
        <div class="menu-content-description">マイク練の予約はこちらから</div>
      </div>
      <% end %>
      <%= link_to("/submit/room") do %>
      <div class="user-menu-content">
        <div class="menu-content-img"></div>
        <div class="menu-content-title">部屋利用掲示板</div>
        <div class="menu-content-description">練習室や部室など、練習場所に関する掲示板です</div>
      </div>
      <% end %>
      <%= link_to("/submit/entry") do %>
      <div class="user-menu-content">
        <div class="menu-content-img"></div>
        <div class="menu-content-title">各種エントリー ※早稲田祭では使用しません</div>
        <div class="menu-content-description">ライブやイベントにエントリーできます</div>
      </div>
      <% end %>
      <%= link_to("/submit/comment") do %>
      <div class="user-menu-content">
        <div class="menu-content-img"></div>
        <div class="menu-content-title">講評・コメント※未実装です</div>
        <div class="menu-content-description">オーディション講評・総会プレゼンへのコメントはこちら</div>
      </div>
      <% end %>
      <%= link_to("/bands") do %>
      <div class="user-menu-content">
        <div class="menu-content-img"></div>
        <div class="menu-content-title">正規バンド一覧</div>
        <div class="menu-content-description">SCS正規バンドの一覧です（新人バンドも含む）</div>
      </div>
      <% end %>
      <%= link_to(new_band_path) do %>
      <div class="user-menu-content">
        <div class="menu-content-img"></div>
        <div class="menu-content-title">正規バンドの申請</div>
        <div class="menu-content-description">正規バンドの申請はこちらから</div>
      </div>
      <% end %>
      <%= link_to("/submit/temporal-band") do %>
      <div class="user-menu-content">
        <div class="menu-content-img"></div>
        <div class="menu-content-title">企画バンドの申請</div>
        <div class="menu-content-description">企画バンドの申請はこちらから</div>
      </div>
      <% end %>
    </div>
  </div>
</div>